# Generated by Django 3.2 on 2023-09-03 18:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone Number Must be entered in the Country Code Format', regex='^(\\+\\d{0,13}|\\s*)?$')])),
                ('password', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=1000)),
                ('state', models.CharField(max_length=100)),
                ('gre_given', models.BooleanField(blank=True, default=False, null=True)),
                ('gre_waiveoff', models.BooleanField(blank=True, default=False, null=True)),
                ('gre_score_quant_verbal', models.CharField(blank=True, default='0', max_length=100, null=True)),
                ('gre_score_awa', models.CharField(blank=True, default='0', max_length=100, null=True)),
                ('toefl_given', models.BooleanField(default=False)),
                ('ielts_given', models.BooleanField(default=False)),
                ('toefl_score', models.CharField(blank=True, default='0', max_length=100, null=True)),
                ('ielts_bands', models.CharField(blank=True, default='0', max_length=100, null=True)),
                ('noofprojects', models.CharField(blank=True, default='0', max_length=100, null=True)),
                ('has_relevant_work_ex', models.CharField(blank=True, default=False, max_length=100, null=True)),
                ('work_ex_years', models.CharField(blank=True, default='0', max_length=100, null=True)),
                ('noof_research_papers', models.CharField(blank=True, default='0', max_length=100, null=True)),
                ('noof_patents', models.CharField(blank=True, default='0', max_length=100, null=True)),
                ('noof_conference_papers', models.CharField(blank=True, default='0', max_length=100, null=True)),
                ('grade', models.CharField(blank=True, default='0', max_length=100, null=True)),
                ('max_possible_grade', models.CharField(blank=True, default='10', max_length=100, null=True)),
                ('profile_score', models.CharField(blank=True, default='0', max_length=100, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
            },
        ),
        migrations.CreateModel(
            name='Universities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uni_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('uni_code', models.CharField(blank=True, max_length=5, null=True)),
                ('course', models.CharField(blank=True, max_length=1000, null=True)),
                ('picture', models.CharField(blank=True, max_length=1000, null=True)),
                ('preferred_profile_score', models.CharField(blank=True, default='0', max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Universitie',
            },
        ),
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(blank=True, max_length=256, null=True)),
                ('otp_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OTP',
            },
        ),
    ]
