# Generated by Django 3.2 on 2023-09-04 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collcalc', '0002_auto_20230903_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='universities',
            name='world_ranking',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
