# Generated by Django 3.2 on 2023-09-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collcalc', '0004_auto_20230904_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='noof_relevant_courses',
            field=models.CharField(blank=True, default='0', max_length=4, null=True),
        ),
    ]
