# Generated by Django 3.2 on 2023-09-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collcalc', '0005_user_noof_relevant_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
